image: node:20-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - dentist-ui/node_modules
    - middleware/dentistApiServer/node_modules
    - middleware/node_modules
    - middleware/patientServer/node_modules
    - middleware/slotService/node_modules
    - patient-ui/node_modules

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - cd dentist-ui
    - npm install
    - npm install --save-dev vite

    - cd ..
    - cd middleware
    - cd patientServer
    - npm install

    - cd ..
    - cd slotService
    - npm install

    - cd ..
    - cd databaseHandler
    - npm install
    - npm install mongoose

    - cd ..
    - cd dentistApiServer
    - npm install
    - npm install cross-env --save-dev
    - npm install mongoose

    - cd ..
    - cd ..
    - cd patient-ui
    - npm install
    - npm install --save-dev vite

test:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  variables:
    MONGODB_URL: "mongodb://mongo:27017/serverTestDB"
  script:
    - cd middleware/dentistApiServer/resources
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "brokerUrl :\"$BROKER_URL\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."
    - npm install
    - npm install npm-run-all --save-dev
    - npm install --include=dev
    - npm install cross-env --save-dev
    - npm install mongoose

    - cd ..
    - cd ../databaseHandler/resources
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "brokerUrl :\"$BROKER_URL\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."

    - cd ..
    - cd ../patientServer/resources
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "brokerUrl :\"$BROKER_URL\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."

    - cd ..
    - cd ../slotService/resources
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "brokerUrl :\"$BROKER_URL_DENTIST\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."

    - cd ..
    - cd ../slotAvailability/resources
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "publicBroker :\"$BROKER_URL_PUBLIC\"," >> credentials.js
    - echo "internalBroker :\"$BROKER_URL_PATIENT\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."

    - cd ..
    - cd ../notificationService/resources
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "brokerUrl :\"$BROKER_URL_PATIENT\"," >> credentials.js
    - echo "email_app_password :\"$EMAIL_PASSWORD\"," >> credentials.js
    - echo "email :\"$EMAIL\"," >> credentials.js
    - echo "notificationCancel :\"$NOTIFICATION_CANCEL\"," >> credentials.js

    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."

    - cd ../.. # Change back to middleware

    # NotificationService tests
    - echo "Running tests for notificationService..."
    - cd notificationService
    - npm install
    - npm run test:unit
    - cd ..

    # SlotAvailability tests
    - echo "Running tests for slotAvailability..."
    - cd slotAvailability
    - npm install
    - npm run test:unit
    - cd ..

    # SlotService tests
    - echo "Running tests for slotService..."
    - cd slotService
    - npm install
    - npm run test:unit
    - cd ..
