image: node:20-alpine

# Cache modules in between jobs per-branch
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - dentist-ui/dentist-client/node_modules
    - middleware/dentistApiServer/node_modules
    - middleware/node_modules
    - middleware/patientServer/node_modules
    - middleware/slotService/node_modules
    - patient-ui/node_modules

stages:
  - build
  - test

build:
  stage: build
  tags:
    - docker
  script:
    - cd dentist-ui/dentist-client
    - npm install
    - npm install --save-dev vite

    - cd ..

    - cd ..
    - cd middleware
    - cd patientServer
    - npm install 

    - cd ..
    - cd slotService
    - npm install

    - cd ..
    - cd databaseHandler
    - npm install
    - npm install mongoose

    - cd .. 
    - cd dentistApiServer
    - npm install
    - npm install cross-env --save-dev
    - npm install mongoose


    - cd ..
    - cd ..
    - cd patient-ui
    - npm install
    - npm install --save-dev vite

test:
  stage: test
  tags:
    - docker
  services:
    - name: mvertes/alpine-mongo:latest
      alias: mongo
  variables:
    MONGODB_URL: "mongodb://mongo:27017/serverTestDB"
  script:

    - cd middleware
    - cd dentistApiServer
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "brokerUrl :\"$BROKER_URL\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."
    - npm install
    - npm install npm-run-all --save-dev
    - npm install --include=dev
    - npm install cross-env --save-dev
    - npm install mongoose
    - npm run ci-test

    - cd ..
    - cd databaseHandler
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "brokerUrl :\"$BROKER_URL\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."

    - cd ..
    - cd patientServer
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "brokerUrl :\"$BROKER_URL\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."
    - npm run ci-test

    - cd ..
    - cd slotService
    - echo "Creating credentials.js..."
    - echo "module.exports = {" > credentials.js
    - echo "broker_url :\"$BROKER_URL\"," >> credentials.js
    - echo "testMongodbUrl :\"$MONGODB_URL\"," >> credentials.js
    - echo "};" >> credentials.js
    - echo "credentials.js created successfully."