services:
  databasehandler:
    build:
      context: ./middleware/databaseHandler
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - patientserver
    networks:
      - backend

  patientserver:
    build:
      context:
        ./middleware/patientserver
    ports:
      - "3001:3001"
    restart:
      always
    networks:
      - backend

  slotavavailabilityservice:
    build:
      context:
       ./middleware/slotAvailability
    depends_on:
      - mosquitto
    restart:
      always
    networks:
      - backend

  dentistserver:
    build:
      context: 
        ./middleware/dentistserver
    ports:
      - "3000:3000"
    networks:
      - backend

  slotservice:
    build:
      context:
        ./middleware/slotservice
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge