services:
  databasehandler:
    build:
      context: ./middleware/databaseHandler
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/dentist_app
    depends_on:
      - mongodb
    networks:
      - backend

  dentistapiserver:
    build:
      context: 
        ./middleware/dentistapiserver
    deploy:
      replicas: 3
    restart:
      always
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./middleware/mosquitto/public/config:/mosquitto/config
      - ./middleware/mosquitto/public/data:/mosquitto/data
      - ./middleware/mosquitto/public/log:/mosquitto/log
    networks:
      - backend
  
  mosquittodentist:
    image: eclipse-mosquitto:latest
    ports:
      - "1885:1885"
    volumes:
      - ./middleware/mosquitto/dentist/config:/mosquitto/config
      - ./middleware/mosquitto/dentist/data:/mosquitto/data
      - ./middleware/mosquitto/dentist/log:/mosquitto/log
    networks:
      - backend

  mosquittopatient:
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1884"
    volumes:
      - ./middleware/mosquitto/patient/config:/mosquitto/config
      - ./middleware/mosquitto/patient/data:/mosquitto/data
      - ./middleware/mosquitto/patient/log:/mosquitto/log
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - patientserver
    networks:
      - backend

  notificationservice:
    build:
      context:
        ./middleware/notificationService
    networks:
      - backend
    depends_on:
      - mosquittopatient

  patientdatabasehandler:
    build:
      context:
        ./middleware/patientDatabaseHandler
    environment: 
      - MONGODB_URL=mongodb://mongodb:27017/dentist_app
    depends_on: 
      - mongodb
    networks:
      - backend

  patientserver:
    build:
      context:
        ./middleware/patientserver
    deploy:
      replicas: 3
    restart:
      always
    networks:
      - backend

  scheduleservice:
    build:
      context:
        ./middleware/scheduleservice
    networks:
      - backend
    depends_on:
      - mosquittodentist

  slotavailability:
    build:
      context:
       ./middleware/slotAvailability
    depends_on:
      - mosquitto
      - mosquittopatient
    restart:
      always
    networks:
      - backend

  slotavailabilityservice:
    build:
      context:
       ./middleware/slotAvailabilityService
    depends_on:
      - mosquitto
    restart:
      always
    networks:
      - backend

  slotbookingservice:
    build:
      context:
       ./middleware/slotBookingService
    depends_on:
      - mosquitto
    restart:
      always
    networks:
      - backend  

  slotservice:
    build:
      context:
        ./middleware/slotservice
    depends_on:
      - mosquittodentist
    networks:
      - backend
    restart: always

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge