services:
  databasehandler:
    build:
      context: ./middleware/databaseHandler
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - patientserver
    networks:
      - backend

  patientserver:
    build:
      context:
        ./middleware/patientserver
    networks:
      - backend

  dentistapiserver:
    build:
      context: 
        ./middleware/dentistapiserver
    ports:
      - "3000:3000"
    networks:
      - backend

  slotservice:
    build:
      context:
        ./middleware/slotservice
    networks:
      - backend

  scheduleservice:
    build:
      context:
        ./middleware/scheduleservice
    networks:
      - backend

  mosquittopatient:
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1884"
      - "9004:9004"
    volumes:
       - ${PWD}/mosquitto/patient/config/mosquitto.conf
       - ${PWD}/mosquitto/patient/data:/mosquitto/data
       - ${PWD}/mosquitto/patient/log:/mosquitto/log
    networks:
      - backend

  mosquittodentist:
    image: eclipse-mosquitto:latest
    ports:
      - "1885:1885"
      - "9005:9005"
    volumes:
      - ${PWD}/mosquitto/dentist/config/mosquitto.conf
      - ${PWD}/mosquitto/dentist/data:/mosquitto/data
      - ${PWD}/mosquitto/dentist/log:/mosquitto/log
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge