services:
  databasehandler:
    build:
      context: ./middleware/databaseHandler
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  dentistserver:
    build:
      context: 
        ./middleware/dentistserver
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  mongodb_data: