services:
  databasehandler:
    build:
      context: ./middleware/databaseHandler
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"