services:
  databasehandler:
    build:
      context: ./middleware/databaseHandler
    env_file:
      - .env
    environment:
      MONGODB_URI: ${MONGODB_URI}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - patientserver

  patientserver:
    build:
      context:
        ./middleware/patientserver
    environment:
      - PORT=3000

  dentistserver:
    build:
      context: 
        ./middleware/dentistserver
    ports:
      - "3001:3000"

  slotservice:
    build:
      context:
        ./middleware/slotservice

volumes:
  mongodb_data: