services:
  databasehandler:
    build:
      context: ./middleware/databaseHandler
    depends_on:
      - mongodb
    networks:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - patientserver
    networks:
      - backend

  patientserver:
    build:
      context:
        ./middleware/patientserver
    environment:
      - PORT=3000
    networks:
      - backend

  dentistserver:
    build:
      context: 
        ./middleware/dentistserver
    ports:
      - "3001:3000"
    networks:
      - backend

  slotservice:
    build:
      context:
        ./middleware/slotservice
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge