services:
  databasehandler:
    build:
      context: ./middleware/databaseHandler
    depends_on:
      - mongodb
    networks:
      - backend
    deploy:
      replicas: 3  # Scale to 3 instances

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/public/config:/mosquitto/config
      - ./mosquitto/public/data:/mosquitto/data
      - ./mosquitto/public/log:/mosquitto/log
    networks:
      - backend

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - patientserver
    networks:
      - backend

  patientserver:
    build:
      context:
        ./middleware/patientserver
    ports:
      - "3001:3001"
    restart:
      always
    networks:
      - backend

  slotavavailabilityservice:
    build:
      context:
       ./middleware/slotAvailability
    depends_on:
      - mosquitto
    restart:
      always
    networks:
      - backend
    deploy:
      replicas: 3  # Scale to 2 instances

  dentistapiserver:
    build:
      context: 
        ./middleware/dentistapiserver
    networks:
      - backend
    deploy:
      replicas: 3  # Scale to 2 instances

  monitoringService:
    build:
      context: 
        .middleware/monitoringService
    networks: 
      - backend
    deploy: 
      replicas: 2 # scale to 2 instances 

  slotservice:
    build:
      context:
        ./middleware/slotservice
    networks:
      - backend
    restart: always

  scheduleservice:
    build:
      context:
        ./middleware/scheduleservice
    networks:
      - backend

  mosquittopatient:
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1884"
    volumes:
      - ./mosquitto/patient/config:/mosquitto/config
      - ./mosquitto/patient/data:/mosquitto/data
      - ./mosquitto/patient/log:/mosquitto/log
    networks:
      - backend

  mosquittodentist:
    image: eclipse-mosquitto:latest
    ports:
      - "1885:1885"
    volumes:
      - ./mosquitto/dentist/config:/mosquitto/config
      - ./mosquitto/dentist/data:/mosquitto/data
      - ./mosquitto/dentist/log:/mosquitto/log
    networks:
      - backend

volumes:
  mongodb_data:

networks:
  backend:
    driver: bridge